.Dd November 30, 2018
.Dt RUNEFLOW 1
.Os
.Sh NAME
.Nm runeflow
.Nd manage and monitor your servers from the cloud
.Sh SYNOPSIS
.Nm runeflow
.Ar action
.Op Ar flags
.Sh FILES
.Ss /etc/runeflow/runeflow.yml
This is the main configuration file for the Runeflow agent. See
.Xr runeflow.yml 5
for additional information.
